"use client";
import { useRouter } from "next/navigation";
import { useState } from "react";
export function FollowUpActions({ signalId }: { signalId: string }) {
  const router = useRouter(); const [status, setStatus] = useState<"REVIEWED" | "SNOOZED" | "RESOLVED" | "DISMISSED">("REVIEWED"); const [note, setNote] = useState(""); const [snoozedUntil, setSnoozedUntil] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [confirmDismiss, setConfirmDismiss] = useState(false);
  async function submit() { if (status === "DISMISSED" && !confirmDismiss) { setConfirmDismiss(true); return; } setError(""); setBusy(true); try { const body = { status, note: note || undefined, snoozedUntil: status === "SNOOZED" && snoozedUntil ? new Date(snoozedUntil).toISOString() : undefined }; const response = await fetch(`/api/v1/admin/follow-up-signals/${signalId}/review`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => null) as { error?: string } | null; if (!response.ok) { setError(payload?.error ?? "Unable to update follow-up."); return; } router.refresh(); } catch { setError("Unable to update follow-up."); } finally { setBusy(false); } }
  return <div className="mt-3 space-y-2"><div className="flex flex-wrap gap-2"><select value={status} onChange={(event) => { setStatus(event.target.value as typeof status); setConfirmDismiss(false); }} className="rounded-lg border border-black/10 p-2 text-sm"><option value="REVIEWED">Mark reviewed</option><option value="SNOOZED">Snooze</option><option value="RESOLVED">Resolve</option><option value="DISMISSED">Dismiss</option></select><button type="button" onClick={submit} disabled={busy} className="rounded-full bg-accent px-4 py-2 text-sm text-white">{busy ? "Saving..." : confirmDismiss ? "Confirm dismiss" : "Save"}</button></div>{confirmDismiss ? <p className="text-sm text-red-700">Dismiss this follow-up as not actionable? Press Confirm dismiss to continue.</p> : null}{status === "SNOOZED" ? <input type="datetime-local" value={snoozedUntil} onChange={(event) => setSnoozedUntil(event.target.value)} className="rounded-lg border border-black/10 p-2 text-sm" /> : null}<textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={500} placeholder="Optional note" className="w-full rounded-lg border border-black/10 p-2 text-sm" /><p className="text-xs text-muted">{note.length}/500</p>{error ? <p className="text-sm text-red-700">{error}</p> : null}</div>;
}
